const SB='https://dxvqiiawthxwkypvsxci.supabase.co',KEY='sb_publishable_Zno2VuYH9oev89OpttorUA_wzNb0EP6',API=SB+'/functions/v1/urna-pesquisa-api';
const $=id=>document.getElementById(id);let session=null,profile=null,cargos=[],cands=[],cfg={layout:{},sons:{},pesquisa:{}},step=0,typed='',blank=false,mode='pesquisa',currentInterview=null,db=null,photoUrls=new Map(),voteHistory=[];
const uuid=()=>crypto.randomUUID?crypto.randomUUID():'loc-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function show(id){['authView','modeView','startView','voteView'].forEach(x=>$(x).classList.toggle('hidden',x!==id))}
function net(){const online=navigator.onLine;$('netStatus').textContent=online?'ONLINE':'OFFLINE';$('netStatus').className='status '+(online?'ok':'warn');return online}
window.addEventListener('online',()=>{net();syncPending()});window.addEventListener('offline',net);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('urna_educativa_local',4);r.onupgradeneeded=()=>{const d=r.result;['meta','interviews','photos'].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:'id'})})};r.onsuccess=()=>{db=r.result;resolve(db)};r.onerror=()=>reject(r.error)})}
function tx(store,mode='readonly'){return db.transaction(store,mode).objectStore(store)}
function put(store,obj){return new Promise((res,rej)=>{const r=tx(store,'readwrite').put(obj);r.onsuccess=()=>res(obj);r.onerror=()=>rej(r.error)})}
function get(store,id){return new Promise((res,rej)=>{const r=tx(store).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function all(store){return new Promise((res,rej)=>{const r=tx(store).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function del(store,id){return new Promise((res,rej)=>{const r=tx(store,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function api(action,opt={}){const h={'Content-Type':'application/json'};if(session?.access_token)h.Authorization='Bearer '+session.access_token;const r=await fetch(API+'?action='+action,{...opt,headers:{...h,...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok){const e=Error(d.error||'Erro de comunicação');e.status=r.status;e.data=d;throw e}return d}
async function authToken(email,password){const r=await fetch(SB+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error_description||d.message||'Falha no login');return d}
function saveSession(s){session=s;localStorage.setItem('urna_session',JSON.stringify(s))}
function clearSession(){session=null;localStorage.removeItem('urna_session')}
async function saveBootstrap(b){profile=b.pesquisador;cargos=b.cargos||[];cands=b.candidatos||[];await put('meta',{id:'bootstrap',value:b,updatedAt:Date.now()})}
async function loadBootstrap(){const m=await get('meta','bootstrap');if(!m)return false;profile=m.value.pesquisador;cargos=m.value.cargos||[];cands=m.value.candidatos||[];return true}
async function saveConfig(){await put('meta',{id:'config',value:cfg,updatedAt:Date.now()})}
async function loadConfigOnline(){const r=await fetch(SB+'/rest/v1/urna_configuracoes?select=chave,valor',{headers:{apikey:KEY,Authorization:'Bearer '+session.access_token}});if(!r.ok)throw Error('config');const d=await r.json();cfg={layout:{},sons:{},pesquisa:{}};(d||[]).forEach(x=>cfg[x.chave]=x.valor||{});await saveConfig()}
async function loadConfigLocal(){const m=await get('meta','config');if(m)cfg=m.value||cfg}
function applyConfig(){const l=cfg.layout||{},s=cfg.sons||{};$('appTitle').textContent=l.titulo||'Urna Educativa';$('intro').textContent=l.texto_abertura||'Participação voluntária. Esta pesquisa não registra voto oficial.';['Phone','City','District','Age','Sex'].forEach(()=>{});$('fPhone').classList.toggle('hidden',l.mostrar_telefone===false);$('fCity').classList.toggle('hidden',l.mostrar_municipio===false);$('fDistrict').classList.toggle('hidden',l.mostrar_bairro===false);$('fAge').classList.toggle('hidden',l.mostrar_faixa_etaria===false);$('fSex').classList.toggle('hidden',l.mostrar_sexo===false);$('consentWrap').classList.toggle('hidden',l.mostrar_consentimento===false);if(window.NativeAudio?.configure)NativeAudio.configure(s.tecla_data||'',s.confirmacao_data||'',s.fim_data||'')}
function playData(data){if(!data)return;try{const a=new Audio(data);a.play().catch(()=>{})}catch(e){}}
function keySound(){const s=cfg.sons||{};if(s.tecla_ativo===false)return;if(window.NativeAudio?.playKey)NativeAudio.playKey();else playData(s.tecla_data)}
function confirmSound(){const s=cfg.sons||{};if(s.confirmacao_ativo===false)return;if(window.NativeAudio?.playConfirm)NativeAudio.playConfirm();else playData(s.confirmacao_data)}
function finishSound(){const s=cfg.sons||{};if(s.fim_ativo===false)return;if(window.NativeAudio?.playFinish)NativeAudio.playFinish();else playData(s.fim_data||s.confirmacao_data)}
async function enterApp(){let got=false;if(net()){try{const b=await api('bootstrap');await saveBootstrap(b);await loadConfigOnline();got=true}catch(e){if(e.data?.status==='pendente'||e.status===403){$('authErr').textContent=e.message;show('authView');return}}}if(!got){got=await loadBootstrap();await loadConfigLocal()}if(!got){show('authView');$('authErr').textContent='Este aparelho ainda não foi preparado para uso offline. Conecte à internet e entre uma vez.';return}applyConfig();$('researcherName').textContent=profile.nome;$('routine').textContent='Meta diária: '+(profile.meta_diaria||10)+' entrevistas'+(profile.horario_inicio?' • Rotina '+profile.horario_inicio.slice(0,5)+(profile.horario_fim?'–'+profile.horario_fim.slice(0,5):''):'');$('adminLink').classList.toggle('hidden',profile.papel!=='admin');$('logoutBtn').classList.remove('hidden');await refreshOfflineInfo();show('modeView');if(net())syncPending()}
async function login(){$('authErr').textContent='';if(!net()){const ok=await loadBootstrap();if(ok){await loadConfigLocal();applyConfig();return enterApp()}return $('authErr').textContent='Primeiro acesso precisa de internet.'}try{const d=await authToken($('loginEmail').value.trim(),$('loginPass').value);saveSession(d);await enterApp()}catch(e){$('authErr').textContent=e.message}}
async function signup(){$('signupErr').textContent='';$('signupOk').textContent='';if(!net())return $('signupErr').textContent='Para criar conta é necessário internet.';const nome=$('signupName').value.trim(),email=$('signupEmail').value.trim(),senha=$('signupPass').value;if(nome.length<3)return $('signupErr').textContent='Informe seu nome completo.';if(!email.includes('@'))return $('signupErr').textContent='Informe um e-mail válido.';if(senha.length<6)return $('signupErr').textContent='A senha precisa ter pelo menos 6 caracteres.';try{const r=await fetch(API+'?action=signup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nome,email,senha})}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Não foi possível criar a conta.');$('signupOk').textContent='Solicitação enviada. Aguarde a aprovação do administrador.'}catch(e){$('signupErr').textContent=e.message}}
async function photoBlob(c){if(!c?.foto_url)return '';if(photoUrls.has(c.foto_url))return photoUrls.get(c.foto_url);const p=await get('photos',c.foto_url);if(p?.blob){const u=URL.createObjectURL(p.blob);photoUrls.set(c.foto_url,u);return u}return c.foto_url}
async function prepareOffline(){if(!net())return $('offlineProgress').textContent='Conecte à internet para preparar o aparelho.';$('prepareOffline').disabled=true;try{const b=await api('bootstrap');await saveBootstrap(b);await loadConfigOnline();applyConfig();let list=cands.filter(c=>c.foto_url),done=0,fail=0,index=0,workers=8;const work=async()=>{while(index<list.length){const i=index++,c=list[i];try{const old=await get('photos',c.foto_url);if(!old?.blob){const r=await fetch(c.foto_url,{cache:'force-cache'});if(!r.ok)throw Error('foto');await put('photos',{id:c.foto_url,blob:await r.blob()})}done++}catch(e){fail++}$('offlineProgress').textContent=`Fotos: ${done+fail}/${list.length} • ${fail} falhas`;}};await Promise.all(Array.from({length:workers},work));await put('meta',{id:'offlineReady',value:true,updatedAt:Date.now()});$('offlineProgress').textContent=`Offline pronto: ${cargos.length} cargos, ${cands.length} candidatos e ${done} fotos armazenadas.`;await refreshOfflineInfo()}catch(e){$('offlineProgress').textContent='Falha ao preparar: '+e.message}finally{$('prepareOffline').disabled=false}}
async function refreshOfflineInfo(){const ready=await get('meta','offlineReady'),ints=await all('interviews'),pending=ints.filter(x=>x.status==='concluida'&&!x.synced).length,conf=ints.filter(x=>x.syncStatus==='conflito').length;$('offlineTitle').textContent=ready?.value?'✅ OFFLINE PRONTO':'⚠️ OFFLINE AINDA NÃO PREPARADO';$('offlineInfo').textContent=`${pending} pesquisa(s) aguardando sincronização${conf?' • '+conf+' conflito(s)':''}.`;const today=new Date().toDateString(),n=ints.filter(x=>x.status==='concluida'&&new Date(x.finishedAt).toDateString()===today).length;$('summary').textContent=`Hoje neste aparelho: ${n} entrevista(s) concluída(s).`}
function office(){return cargos[step]||null}function candidate(){const o=office();return o?cands.find(c=>String(c.cargo_id)===String(o.id)&&String(c.numero)===typed)||null:null}function repeatedSenator(c,o){if(!c||!o||!/Senador/i.test(o.nome)||!/2/.test(o.nome))return false;const first=voteHistory.find(a=>/Senador/i.test(a.cargo_nome)&&a.tipo_resposta==='candidato');return !!first&&String(first.numero_digitado)===String(typed)}
function beginVote(m){mode=m;step=0;typed='';blank=false;currentInterview=null;voteHistory=[];$('voteModeLabel').textContent=m==='treino'?'TREINAMENTO • SEU VOTO PARA':'PESQUISA • SEU VOTO PARA';show('voteView');render()}
async function render(){const o=office();if(!o){$('screen').innerHTML=`<div class="finish"><b>FIM</b><span>${mode==='treino'?'Treinamento concluído — nada foi gravado.':'Pesquisa salva no celular. '+(navigator.onLine?'Sincronizando…':'Será sincronizada quando houver internet.')}</span><button class="primary" onclick="novaEntrevista()">NOVA PESQUISA</button></div>`;finishSound();if(mode==='pesquisa'&&currentInterview){currentInterview.status='concluida';currentInterview.finishedAt=new Date().toISOString();await put('interviews',currentInterview);refreshOfflineInfo();if(net())syncPending()}return}$('office').textContent=o.nome;$('digits').innerHTML=Array.from({length:o.digitos},(_,i)=>`<div class="digit">${typed[i]||''}</div>`).join('');let c=candidate();const dup=repeatedSenator(c,o),full=typed.length===Number(o.digitos),isNull=!blank&&full&&(!c||dup);$('blankLabel').textContent=blank?'VOTO EM BRANCO':'VOTO NULO';$('blankLabel').classList.toggle('show',blank||isNull);$('cand').classList.toggle('show',!!c&&!blank&&!dup);if(c&&!dup){$('cname').textContent=c.nome;$('cparty').textContent=(c.partido||'')+' • '+c.numero;$('cphoto').src=await photoBlob(c)}}
function restoreVoteScreen(){$('screen').innerHTML='<small id="voteModeLabel">SEU VOTO PARA</small><div class="office" id="office"></div><div>Digite o número do candidato.</div><div class="digits" id="digits"></div><div class="cand" id="cand"><div><h2 id="cname"></h2><b id="cparty"></b></div><img id="cphoto"></div><div class="blank" id="blankLabel">VOTO EM BRANCO</div>'}
function novaEntrevista(){restoreVoteScreen();step=0;typed='';blank=false;voteHistory=[];currentInterview=null;if(mode==='treino'){show('modeView');return}['name','phone','city','district','address'].forEach(id=>{if($(id))$(id).value=''});if($('age'))$('age').value='';if($('sex'))$('sex').value='';if($('consent'))$('consent').checked=false;$('startErr').textContent='';show('startView')}

async function startResearch(){$('startErr').textContent='';const consent=$('consent').checked;if(!consent)return $('startErr').textContent='Confirme o consentimento.';const phone=$('phone').value.replace(/\D/g,'');if((cfg.pesquisa||{}).telefone_obrigatorio!==false&&phone.length<8)return $('startErr').textContent='Informe o telefone do participante.';const ints=await all('interviews');if((cfg.pesquisa||{}).bloquear_repeticao!==false&&phone&&ints.some(x=>x.phone===phone&&x.status==='concluida'))return $('startErr').textContent='Este telefone já respondeu neste aparelho.';currentInterview={id:uuid(),createdAt:new Date().toISOString(),finishedAt:null,status:'em_andamento',synced:false,syncStatus:'pendente',serverId:null,phone,participant:{nome:$('name').value.trim()||null,telefone:phone||null,municipio:$('city').value.trim()||null,bairro:$('district').value.trim()||null,endereco:$('address').value.trim()||null,faixa_etaria:$('age').value||null,sexo:$('sex').value||null,consentimento:true},answers:[]};await put('interviews',currentInterview);step=0;typed='';blank=false;voteHistory=[];mode='pesquisa';$('voteModeLabel').textContent='PESQUISA • SEU VOTO PARA';show('voteView');render()}
async function confirmVote(){const o=office();if(!o)return;if(!blank&&typed.length!==Number(o.digitos))return;let c=candidate(),tipo='nulo';const dup=repeatedSenator(c,o);if(blank)tipo='branco';else if(c&&!dup)tipo='candidato';else{tipo='nulo';c=null}const answer={cargo_id:o.id,cargo_nome:o.nome,candidato_id:c?.id||null,numero_digitado:typed||null,tipo_resposta:tipo,ordem:step+1};voteHistory.push(answer);if(mode==='pesquisa'&&currentInterview){currentInterview.answers.push({cargo_id:answer.cargo_id,candidato_id:answer.candidato_id,numero_digitado:answer.numero_digitado,tipo_resposta:answer.tipo_resposta,ordem:answer.ordem});await put('interviews',currentInterview)}confirmSound();step++;typed='';blank=false;render()}

async function syncOne(x){if(x.synced||x.status!=='concluida'||!net())return;try{let sid=x.serverId;if(!sid){const s=await api('start',{method:'POST',body:JSON.stringify({...x.participant})});sid=s.entrevista_id;x.serverId=sid;await put('interviews',x)}for(const a of x.answers){await api('answer',{method:'POST',body:JSON.stringify({...a,entrevista_id:sid})})}await api('finish',{method:'POST',body:JSON.stringify({entrevista_id:sid})});x.synced=true;x.syncStatus='sincronizado';await put('interviews',x)}catch(e){if(e.status===409){x.syncStatus='conflito';x.syncError=e.message;await put('interviews',x)}else{x.syncStatus='pendente';x.syncError=e.message;await put('interviews',x)}}}
async function syncPending(){if(!net()||!session?.access_token)return;const list=(await all('interviews')).filter(x=>x.status==='concluida'&&!x.synced&&x.syncStatus!=='conflito');$('offlineProgress').textContent=list.length?'Sincronizando '+list.length+' pesquisa(s)…':'';for(const x of list)await syncOne(x);await refreshOfflineInfo();$('offlineProgress').textContent=list.length?'Sincronização concluída.':''}
function toggleEye(input,btn){const p=$(input);p.type=p.type==='password'?'text':'password';$(btn).textContent=p.type==='password'?'👁':'🙈'}
$('eyeLogin').onclick=()=>toggleEye('loginPass','eyeLogin');$('eyeSignup').onclick=()=>toggleEye('signupPass','eyeSignup');$('loginBtn').onclick=login;$('showSignupBtn').onclick=()=>{$('signupBox').classList.remove('hidden')};$('cancelSignupBtn').onclick=()=>{$('signupBox').classList.add('hidden')};$('signupBtn').onclick=signup;$('prepareOffline').onclick=prepareOffline;$('syncNow').onclick=syncPending;$('researchMode').onclick=()=>show('startView');$('trainingMode').onclick=()=>beginVote('treino');$('backMode').onclick=()=>show('modeView');$('startBtn').onclick=startResearch;$('logoutBtn').onclick=()=>{clearSession();location.reload()};document.querySelectorAll('.key[data-n]').forEach(b=>b.onclick=()=>{const o=office();if(!o||typed.length>=o.digitos)return;keySound();typed+=b.dataset.n;blank=false;render()});$('correctBtn').onclick=()=>{keySound();typed='';blank=false;render()};$('blankBtn').onclick=()=>{keySound();typed='';blank=true;render()};$('confirmBtn').onclick=confirmVote;
(async()=>{await openDB();net();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});try{session=JSON.parse(localStorage.getItem('urna_session')||'null')}catch(e){}if(session)await enterApp();else show('authView')})();